"""Create conversation and message tables

Revision ID: 53a5fdf6368a
Revises: d4f5e0af6762
Create Date: 2025-08-22 23:34:20.267992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53a5fdf6368a'
down_revision: Union[str, Sequence[str], None] = 'd4f5e0af6762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender', sa.Enum('USER', 'BOT', name='messagesender'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.add_column('conversations', sa.Column('thread_id', sa.String(), nullable=False))
    op.add_column('conversations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_conversations_thread_id'), 'conversations', ['thread_id'], unique=True)
    op.drop_column('conversations', 'is_user')
    op.drop_column('conversations', 'message')
    op.drop_column('conversations', 'timestamp')
    op.drop_column('conversations', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('conversations', sa.Column('is_user', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_conversations_thread_id'), table_name='conversations')
    op.drop_column('conversations', 'created_at')
    op.drop_column('conversations', 'thread_id')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
