"""add company_id to doc and web embeddings

Revision ID: 81f1a787e681
Revises: 97a37fb962de
Create Date: 2025-08-15 23:29:28.512954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f1a787e681'
down_revision: Union[str, Sequence[str], None] = '97a37fb962de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_embeddings', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'doc_embeddings', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('documents', 'keywords_search',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('web_embeddings', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'web_embeddings', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_embeddings', type_='foreignkey')
    op.drop_column('web_embeddings', 'company_id')
    op.alter_column('documents', 'keywords_search',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'doc_embeddings', type_='foreignkey')
    op.drop_column('doc_embeddings', 'company_id')
    # ### end Alembic commands ###
