"""Add URL_COMPANY to table Company

Revision ID: 917b68b11ef1
Revises: 2cb9a80a1c27
Create Date: 2025-08-06 20:26:41.121629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '917b68b11ef1'
down_revision: Union[str, Sequence[str], None] = '2cb9a80a1c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('url_company', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_url_company'), 'companies', ['url_company'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_url_company'), table_name='companies')
    op.drop_column('companies', 'url_company')
    # ### end Alembic commands ###
