"""update relationships for company, folder, document

Revision ID: 97a37fb962de
Revises: edea4d295ffe
Create Date: 2025-08-08 00:17:46.235208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a37fb962de'
down_revision: Union[str, Sequence[str], None] = 'edea4d295ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.add_column('folders', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'folders', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_column('folders', 'company_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'folder_id')
    # ### end Alembic commands ###
